### PR TITLE
Create Import Large Files

### PR DESCRIPTION
**Pull request by Tamarael**
A sample script to import large files via the Shared Access Storage

### CODE REVIEW

**Review by VsabGit — APPROVED** [review]

**Comment by Tamarael** [comment]
> 

@microsoft-github-policy-service agree [company="{your company}"]

**Comment by Tamarael** [comment]
@microsoft-github-policy-service agree

**Comment by Tamarael** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Tamarael** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by laurent-mic — APPROVED** [review]

**Comment by Tamarael** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Tamarael** [comment]
@microsoft-github-policy-service agree

**Pull request closed without merging**
