### PR TITLE
Tool to load test Power BI V2

### PR DESCRIPTION
**Pull request by mikeblakeuk**
- [x] Add console tool to test importing PBIX files and setting the connection
- [x] Add support for V1 to compare speeds
- [x] Add Insights logging
- [x] Add log4net for local logging
- [x] Add Config
- [x] Add Tests

### CODE REVIEW

**Comment by eligr** [comment]
I'm sorry, I don't think this is the right place for this.

**Comment by mikeblakeuk** [comment]
@eligr where do you think it should go?
It's super helpful to test Capacity loading

**Comment by eligr** [comment]
Hey @mikeblakeuk !
This repo if for people getting started, we try to not complicate it too much.
I don't argue that you sample in not helpful, i just think it belongs to your own repo.
If you'd like, i can reference it from our blog or documentation.

**Comment by mikeblakeuk** [comment]
Feel free to reference it if you want to.

**Pull request closed without merging**
